### ISSUE TITLE
How to run the code？

### ISSUE THREAD

**Issue by CSC-hzd** [uzh-rpg/vilib#14]
After compiling the library and completing various configurations，I couldn‘t found necessary instructions for running the compiled code of the whole project in the _**readme**_ section，so I want to know how can I start running those codes and how to use the dataset mentioned in the paper. Please add more details about those issues, thanks!

**Comment by foehnx** [comment]
Thank you for the request.

Under point 2 in the readme section [HowToUse](https://github.com/uzh-rpg/vilib#how-to-use) a unit test suite is launched.
The unit test should also work as an example, e.g. for feature tracking you can follow https://github.com/uzh-rpg/vilib/blob/master/visual_lib/test/src/high_level/test_featuretracker.cpp,

@baliika it would be nice if the user is guided to this from the readme.

**Comment by baliika** [comment]
Hi CSC-hzd,
thanks for your comment.
We added more details about the examples and how the dataset is acquired for the test suite on a feature branch that is linked to this issue.
Should you have more queries, please let us know. Thanks!
