### ISSUE TITLE
Compile Error（error: identifier "__shfl_xor_sync" is undefined）

### ISSUE THREAD

**Issue by ThinkPig826** [uzh-rpg/vilib#17]
Sorry, the following error occurred when we compiled the project, I don’t know why.  thank you！

src/feature_tracker/feature_tracker_cuda_tools.cu(146): error: identifier "__shfl_xor_sync" is undefined
          detected during instantiation of "void vilib::feature_tracker_cuda_tools::track_features_kernel<T,affine_est_offset,affine_est_gain>(int, int, int, float, vilib::image_pyramid_descriptor_t, vilib::pyramid_patch_descriptor_t, const int *, const T *, const float *, const float2 *, float2 *, float2 *, float4 *, float *) [with T=int, affine_est_offset=true, affine_est_gain=true]" 
(332): here

src/feature_tracker/feature_tracker_cuda_tools.cu(652): error: a designator into a template-dependent type is not allowed

src/feature_tracker/feature_tracker_cuda_tools.cu(652): error: a designator into a template-dependent type is not allowed

src/feature_tracker/feature_tracker_cuda_tools.cu(677): error: identifier "__syncwarp" is undefined

src/feature_tracker/feature_tracker_cuda_tools.cu(579): error: identifier "__shfl_down_sync" is undefined

**Comment by baliika** [comment]
hi ThinkPig826,
Thanks for your message. Could you share your CUDA version? Also could you try updating it to the latest?
I assume your currently installed CUDA version is 8 or before which does not have these intrinsics.

**Comment by ThinkPig826** [comment]
Thank you very much, this problem has been solved, it is indeed caused by inconsistent versions
