### ISSUE TITLE
The tracking effect is not the same as the function of Opencv

### ISSUE THREAD

**Issue by ThinkPig826** [uzh-rpg/vilib#20]
I transferred the tracked feature points into the vilib library and got the tracking results, which are indicated in white in the picture. Give the same set of coordinates to the OpenCV function calcOpticalFlowPyrLK, and the result is shown in black. By comparison, it is found that some points of vilib are not as good as opencv, and the tracking range is not as long as opencv. Is this normal?
Thanks again!
![Screenshot from 2020-11-11 20-32-37](https://user-images.githubusercontent.com/35769172/98900221-45fca880-24ec-11eb-9ad0-5d4962993a74.png)
![Screenshot from 2020-11-11 20-33-49](https://user-images.githubusercontent.com/35769172/98900232-4eed7a00-24ec-11eb-819e-695bd4a4e17d.png)

**Comment by berndpfrommer** [comment]
I also have issues with tracking not working for larger baselines. Large meaning anything beyond a few pixels. I tried different pyramid levels to no avail. Not sure if it's user error. Any pointers on how to debug this?

**Comment by berndpfrommer** [comment]
A good deal of my issues went away when disabling the affine illumination matching in the KLT tracker (affine_est_offset = false and affine_est_gain = false)
