### ISSUE TITLE
Ask for documentation

### ISSUE THREAD

**Issue by shockwaveHe** [uzh-rpg/vilib#27]
Hi! I am impressed about your work and trying to use the library in one of my project to do feature detection and tracking. However, the lack of documentation adds a lot of difficulties for me. Can you update some documentation about how to use  the library?

**Comment by foehnx** [comment]
I added an implementation of our feature tracker which provides a ROS node and could be used as an example of how to deploy our work.
Feel free to check it out in the new [ros folder](https://github.com/uzh-rpg/vilib/tree/master/ros), with instructions in the [README](https://github.com/uzh-rpg/vilib#ros-quick-start).
Unfortunately, I do not have time to follow up on the documentation at the moment, but might do so later on.
