### ISSUE TITLE
OpenCV parameter compatibility 

### ISSUE THREAD

**Issue by limhyon** [uzh-rpg/vilib#6]
Hi,
We are currently testing faster than fast tracker compared to OpenCV calcOpticalFlowPyrLK on KITTI dataset.
We have observed that two methods outputs significantly different sometimes.
Have you ever tested conformity of the proposed tracker to OpenCV’s calcOpticalFlowPyrLK? If so, could you let us know the parameters that you were using?

**Comment by baliika** [comment]
Hi limhyon,
Thank you for inquiry.
Our implementation follows the algorithm(s) presented in [1], and there might be subtle differences in tracker algorithms that may cause their outputs to differ: employed pyramid levels, termination criteria, window size, interpolation/no interpolation of the template patch, non-associativity of floating point operations, floating-point precision, etc. In contrast, the FAST feature detector is a really well-defined algorithm (bonus, it is based on integer operations), for which we could easily come up with a comparison framework. For the above reasons, for the feature tracker, we did not perform conformity tests, apart from the tests we performed to measure its runtime.

References:
1. Lucas-Kanade 20 Years On: A Unifying Framework: Part 1, Part2, and Part3
